### ISSUE TITLE
Cleaner module installation without CLI dependencies

### ISSUE THREAD

**Issue by dgw** [nkrim/spongemock#1]
Hiya,

I was surprised and amused to find this module up on PyPI, since it predates my own IRC bot "spongemock" plugin by about two years but I never thought to search for existing packages at the time. The algorithm here is objectively better than my own, because of the tuning parameters made available. It seems like a no-brainer to just replace mine with this.

The hard dependency on `pyperclip` gives me pause, though. It's only needed in a small subset of use cases: when the user both 1) wants to use `spongemock` as a terminal command, _and_ 2) wants to use the `-c` clipboard option.

Ultimately, I thought of four possible ways to eliminate the unneeded dependency:

1. Make `pyperclip` a setuptools extra, so it's only installed if the user requests it.
   - Downside: `-c` option doesn't work "out of the box"; may confuse users
2. Remove `pyperclip` and the `-c` argument entirely; users can generally pipe the output of a command to `xcopy`, `pbcopy`, etc. themselves if they want it on the clipboard.
   - Downside: Breaks scripts/macros that use the `-c` option; may confuse users
3. Extract the module portion of this project to its own package (e.g. `spongemocklib`)
   - Downside: anyone currently relying on `spongemock` from other code will need to update their requirements
4. Extract the CLI portion of this project to its own package (e.g. `spongemock-cli`)
   - Downside: anyone currently using `spongemock` in the terminal would have to install a different package on new installs or after a pip upgrade

In the end, none of the options is free of possible stumbling blocks. But if this was my own five-year-old project, I'd probably take option 3—move the module to its own package, and leave the CLI (with `-c` clipboard option) as-is. I just wanted to drop in here and see if you had any thoughts. (Forking first and asking questions later seems to me that it often causes problems in the long run. 🙂)

**Comment by nkrim** [comment]
Hey there,

I agree that, in retrospect, this is an unfortunate and unnecessary dependency. I think removing it outright (option 2) would be sufficient since, as you said, there are ways to achieve the same effect. Creating a standalone library would also be a good option, but it honestly sounds like more work than is necessary for a little joke project like this. I would be surprised if anyone has scripts dependent on the `-c` flag, so I don't mind getting rid of it.

If you want to fork it and make the adjustments then feel free. Otherwise, I could get to it later this week/weekend. 

Thanks for showing interest : )

**Comment by dgw** [comment]
Created #2 to carry out, appropriately, option 2. Seems like a good excuse to drop v1.0 for the breaking change? 😁

Thanks for getting back to me, too!

**Comment by nkrim** [comment]
Thanks again. I guess I'll take you up on that 1.0 🍾🎉
